### ISSUE TITLE
When moving to another area, music disappears in WebAO

### ISSUE THREAD

**Issue by Dedinsaid228** [Crystalwarrior/KFO-Server#10]
Hello. This bug occurs in any browser, in any version of the browser, regardless of the operating system.
Just in case, I recorded a video:
Microsoft Edge 92.0.902.62 - https://drive.google.com/file/d/1QnYklFA0QLVlBOhDWTD3MtOCwvNUB28v/view?usp=sharing
Mozila Firefox 54 - https://drive.google.com/file/d/1I5VVTvzsEwKGtMmVu0mqaaJYOU8eCWAR/view?usp=sharing
Videos were recorded on Windows 10.

**Comment by Crystalwarrior** [comment]
This occurs due to @stoneDiscord not supporting multiple music channels on webAO, yet accepting KFO 2.8+ MC packets that play music on a different channel.
From KFO-Server's side, this occurs because each area contains an Ambiance music layer, that plays concurrently with the area Music layer. Even if ambiance is not set for an area, it will play a "nothing" ambiance to make sure players' ambiance is properly reset.
I suggest making an issue request on that repository instead https://github.com/AttorneyOnline/webAO

**Comment by Crystalwarrior** [comment]
Should be resolved
