### ISSUE TITLE
Users get kicked from KFO server again, with toggle_passing_IC, even after last update

### ISSUE THREAD

**Issue by Chibiange** [Crystalwarrior/KFO-Server#57]
Okay, so it's seem the last error where toggle_passing_IC caused users to get kicked off the server when it's ON, is back for no reason. I don't know what to do or why it happens again. I got screenshot of the error code thingy if needed.

**Comment by Satoru-1816** [comment]
Sure, it'd be helpful. What does the error says?

**Comment by Chibiange** [comment]
Well, i can send you the screenshot of my server error, if it can make it any easier, on discord if you want.

**Comment by Satoru-1816** [comment]
Aight, can you send it here?

**Comment by Chibiange** [comment]
https://cdn.discordapp.com/attachments/885555851396534282/971103222808846336/unknown.png
Here it is

**Comment by Satoru-1816** [comment]
I'd suggest downloading the latest KFO-server once more, that may fix it 
![image](https://user-images.githubusercontent.com/81326989/166584363-a620f1ad-60f9-4940-9ae7-a14476580483.png)
Line 189 should correspond to "`if len(self.area.pos_lock) > 0:`" instead of "`lst[5] = self.area.pos_lock[0]`" after the latest update

**Comment by Chibiange** [comment]
Okay so... I just realized that it was actually my bad... I had actually downloaded the update of Crystal warrior made, which had the fix but my shortcut for it was using the buggy version.... oops. I fixed it now x:...
